/*
Las medianas de un triángulo son los segmentos que unen los vértices con el punto medio de sus lados opuestos. Las tres medianas de un triángulo se cruzan en un mismo punto, llamado baricentro o centroide.

Dado un triángulo definido por las coordenadas cartesianas de sus tres vértices (A, B y C), necesitamos localizar su baricentro o centroide.

Tu función recibe las coordenadas de los tres vértices A, B y C como tres argumentos diferentes y debe devolver las coordenadas del baricentro O, redondeadas a 4 decimales, en un arreglo [xO, yO].

Sabes que las coordenadas del baricentro se calculan con las siguientes fórmulas:

xO = (xA + xB + xC) / 3
yO = (yA + yB + yC) / 3

Los puntos dados pueden formar un triángulo real o degenerado, pero en ambos casos se pueden usar las fórmulas anteriores.

Para más información sobre este importante punto de un triángulo, consulta: https://es.wikipedia.org/wiki/Centroide

Veamos algunos casos:

([4, 6], [12, 4], [10, 10]) ------> [8.6667, 6.6667]

([4, 2], [12, 2], [6, 10]) ------> [7.3333, 4.6667]

¡Disfruta y feliz programación!
*/

#include <utility>
#include <iostream>

using point = const std::pair<double, double>;

std::pair<double, double> barTriang(point p1, point p2, point p3) {
    double xO = (p1.first + p2.first + p3.first) / 3.0;
    double yO = (p1.second + p2.second + p3.second) / 3.0;

    // Generated by LLM
    // 2. Add these two lines to round the result to 4 decimal places
    xO = (long long)((xO * 10000.0) + (xO > 0 ? 0.5 : -0.5)) / 10000.0;
    yO = (long long)((yO * 10000.0) + (yO > 0 ? 0.5 : -0.5)) / 10000.0;
    //----------------

    return {xO, yO};
}

